<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ATW-7005" name="com.altius.automation.Svcfflow" tests="10" failures="0" timestamp="01 Apr 2019 10:54:20 GMT" time="40.105" errors="1">
  <testcase name="groupadditionhover" time="0.041" classname="com.altius.automation.Svcfflow"/>
  <testcase name="WithoutUNPW" time="2.392" classname="com.altius.automation.Svcfflow"/>
  <testcase name="wrongUN" time="4.931" classname="com.altius.automation.Svcfflow"/>
  <testcase name="groupaddition" time="0.015" classname="com.altius.automation.Svcfflow">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.altius.automation.Groupaddition.groupaddition(Groupaddition.java:261)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- groupaddition -->
  <testcase name="wrongPW" time="2.653" classname="com.altius.automation.Svcfflow"/>
  <testcase name="wrongUNPW" time="2.643" classname="com.altius.automation.Svcfflow"/>
  <testcase name="OnlyCorrectUN" time="3.046" classname="com.altius.automation.Svcfflow"/>
  <testcase name="OnlycorrectPW" time="2.662" classname="com.altius.automation.Svcfflow"/>
  <testcase name="branchname" time="0.352" classname="com.altius.automation.Svcfflow"/>
  <testcase name="OnlyCorrectUNPW" time="21.370" classname="com.altius.automation.Svcfflow"/>
</testsuite> <!-- com.altius.automation.Svcfflow -->
